/**
 * Copyright 2022-2025 kronos-orm
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

tasks.register("generateJoinClause") {
    group = "codegen"
    description = "generate join clauses with maxJoinNum"
    doLast {
        val root = project.layout.projectDirectory.asFile.parent
        val joinDir = File("$root/kronos-core/src/main/kotlin/com/kotlinorm/orm/join")
        val maxJoinNum = 16
        val joinRange = 2..maxJoinNum

        fun generatePatch() {
            val fileName = "Patch.kt"
            with(File(joinDir, fileName)) {
                if (!exists()) {
                    createNewFile()
                }

                writeText(
                    """
                    |/**
                    |* Copyright 2022-2025 kronos-orm
                    |*
                    |* Licensed under the Apache License, Version 2.0 (the "License");
                    |* you may not use this file except in compliance with the License.
                    |* You may obtain a copy of the License at
                    |*
                    |*     http://www.apache.org/licenses/LICENSE-2.0
                    |*
                    |* Unless required by applicable law or agreed to in writing, software
                    |* distributed under the License is distributed on an "AS IS" BASIS,
                    |* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
                    |* See the License for the specific language governing permissions and
                    |* limitations under the License.
                    |*/
                    |
                    |package com.kotlinorm.orm.join
                    |
                    |import com.kotlinorm.beans.dsl.KSelectable
                    |import com.kotlinorm.interfaces.KPojo
                    |import com.kotlinorm.types.ToSelect
                    |import com.kotlinorm.utils.createInstance
                    |import kotlin.reflect.KClass
                    |import kotlin.reflect.typeOf
                    |
                    |// Generated by generate-join-clause.gradle.kts
                    |
                    |@PublishedApi
                    |internal const val DerivedJoinAlias = "q"
                    |
                    |@PublishedApi
                    |@Suppress("UNCHECKED_CAST")
                    |internal inline fun <T1 : KPojo, reified R : KPojo, C : KPojo> SelectFrom<T1, *, *>.selectGeneratedProjection(
                    |    @Suppress("UNUSED_PARAMETER") projectionClass: KClass<R>,
                    |    contextClass: KClass<C>,
                    |    noinline fields: ToSelect<T1, Any?> = null
                    |): SelectFrom<T1, R, C> {
                    |    initializeProjection(typeOf<R>(), typeOf<R?>(), contextClass.createInstance())
                    |    return (this as SelectFrom<T1, R, C>).select(fields)
                    |}
                    |
                    |inline fun <reified T1 : KPojo, reified T2 : KPojo> T1.join(
                    |    query: KSelectable<T2>,
                    |    noinline selectFrom: SelectFrom2<T1, T2>.(T1, T2) -> Unit
                    |): SelectFrom2<T1, T2> {
                    |    val selectedClass = query.selectedType.classifier as KClass<T2>
                    |    val row = selectedClass.createInstance()
                    |    return SelectFrom2(this, row).apply {
                    |        initializeProjection(typeOf<T1>(), typeOf<T1?>())
                    |        registerDerivedJoin(row.__tableName, query, DerivedJoinAlias)
                    |        selectFrom(t1, t2)
                    |    }
                    |}
                    |
                    |${
                        joinRange.joinToString("\n\n") { index ->
                            val range = 1..index
                            val nthOfType = range.joinToString(", ") { "T${it}" }
                            """
                            |inline fun <${range.joinToString(",") { "reified T$it : KPojo" }}> T1.join(
                            |${range.drop(1).joinToString(",\n") { "    table$it: T$it" }},
                            |    selectFrom: SelectFrom$index<$nthOfType>.($nthOfType) -> Unit
                            |): SelectFrom$index<$nthOfType> {
                            |    return SelectFrom$index(this, ${
                                range.drop(1).joinToString(", ") { "table$it" }
                            }).apply {
                            |        initializeProjection(typeOf<T1>(), typeOf<T1?>())
                            |        selectFrom(${range.joinToString(", ") { "t$it" }})
                            |    }
                            |}
                            """.trimMargin()
                        }
                    }
                    """.trimMargin().trimEnd())
            }
        }

        fun generateSelectFromN(n: Int) {
            val fileName = "SelectFrom$n.kt"
            with(File(joinDir, fileName)) {
                if (!exists()) {
                    createNewFile()
                }
                val range = 1..n
                val nthOfType = range.joinToString(", ") { "T${it}" }
                val nthOfConstrainedType = range.joinToString(", ") { "T${it}: KPojo" }
                writeText(
                    """
                        |/**
                        |* Copyright 2022-2025 kronos-orm
                        |*
                        |* Licensed under the Apache License, Version 2.0 (the "License");
                        |* you may not use this file except in compliance with the License.
                        |* You may obtain a copy of the License at
                        |*
                        |*     http://www.apache.org/licenses/LICENSE-2.0
                        |*
                        |* Unless required by applicable law or agreed to in writing, software
                        |* distributed under the License is distributed on an "AS IS" BASIS,
                        |* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
                        |* See the License for the specific language governing permissions and
                        |* limitations under the License.
                        |*/
                        |
                        |package com.kotlinorm.orm.join
                        |
                        |import com.kotlinorm.interfaces.KPojo
                        |import com.kotlinorm.orm.pagination.PagedClause
                        |
                        |// Generated by generate-join-clause.gradle.kts
                        |class SelectFrom$n<$nthOfConstrainedType>(
                        |    t1: T1,
                        |    ${range.drop(1).joinToString(", ") { "var t$it: T$it" }}
                        |) : SelectFrom<T1, T1, T1>(t1) {
                        |    init {
                        |        context.setSources(${range.joinToString(", ") { "t$it" }})
                        |    }
                        |
                        |    fun withTotal(): PagedClause<T1, T1, SelectFrom$n<$nthOfType>> {
                        |        return PagedClause(this)
                        |    }
                        |}
                    """.trimMargin()
                )
            }
        }

        joinDir.listFiles()?.forEach {
            if (it.name == "Patch.kt" || it.name.matches(Regex("SelectFrom\\d+\\.kt"))) {
                it.delete()
            }
        }

        println()

        println("=====================================")
        println("> Start generating join clauses")
        println("=====================================")

        println()

        println("Max join num is $maxJoinNum")
        println("Join clauses will be generated in $joinDir")
        println()

        println("• Generating patch file:")
        generatePatch()
        println("✓ Patch file generated successfully")

        println()

        println("• Generating selectFromN files:")
        val rangeList = joinRange.toList()
        rangeList.forEachIndexed { index, num ->
            println("• Generating SelectFrom${num.toString().padEnd(2, ' ')}.kt\t${index + 1}/${rangeList.size}")
            generateSelectFromN(num)
        }
        println("✓ SelectFromN files generated successfully")

        println()

        println("=====================================")
        println("✓ Join clauses generated successfully")
        println("=====================================")
    }
}
