package com.kotlinorm.plugin.idea.codegen

import com.kotlinorm.beans.dsl.Field
import com.kotlinorm.beans.dsl.KTableIndex
import com.kotlinorm.codegen.KronosTemplate
import com.kotlinorm.codegen.kotlinType
import com.kotlinorm.enums.KColumnType
import com.kotlinorm.enums.PrimaryKeyType
import java.time.LocalDateTime

class KronosIdeaCodegenRenderer {
    fun preview(request: KronosIdeaGenerationRequest): List<KronosIdeaGeneratedFile> {
        require(request.tables.isNotEmpty()) { "Select at least one table." }
        require(request.packageName.isNotBlank()) { "Package name is required." }
        if (request.templateContent == null && request.templateName != BuiltInKPojoName) {
            error("Template '${request.templateName}' is not available. Refresh templates and select a project template file.")
        }

        return request.tables.map { table ->
            val className = table.name.toPascalCase()
            val fields = table.columns.map { it.toField(table.name) }
            val indexes = table.indexes.map { index ->
                KTableIndex(
                    name = index.name,
                    columns = index.columns.toTypedArray(),
                    type = if (index.unique) "UNIQUE" else "",
                )
            }
            val template = KronosTemplate(
                packageName = request.packageName.trim(),
                tableName = table.name,
                className = className,
                tableComment = table.comment,
                fields = fields,
                indexes = indexes,
                tableCommentLineWords = 80,
            )
            val content = request.templateContent?.let { template.renderProjectKPojo(it, request.templateName) }
                ?: template.renderBuiltInKPojo()
            KronosIdeaGeneratedFile(
                tableName = table.name,
                className = className,
                relativePath = "$className.kt",
                content = content,
            )
        }
    }

    private fun KronosTemplate.renderBuiltInKPojo(): String {
        +"package $packageName"
        +""
        +imports.joinToString("\n") { "import $it" }
        +""
        +formatedComment
        +"// @author: Kronos-Codegen"
        +"// @date: ${LocalDateTime.now()}"
        +""
        +"@Table(name = \"$tableName\")"
        +indexes.toAnnotations()
        +"data class $className("
        fields.forEach { field ->
            field.annotations().forEach { annotation ->
                +"${indent(4)}$annotation"
            }
            +"${indent(4)}var ${field.name}: ${field.kotlinType}? = null,"
        }
        +"): KPojo"
        return content
    }

    private fun KronosTemplate.renderProjectKPojo(templateContent: String, templateName: String): String {
        if (!templateContent.contains(IdeaTemplateMarker)) {
            error(
                "Project template '$templateName' is not a supported IDEA KPojo template. " +
                    "Copy the built-in template again or add $IdeaTemplateMarker."
            )
        }
        return templateContent
            .replace("{{packageName}}", packageName)
            .replace("{{imports}}", imports.joinToString("\n") { "import $it" })
            .replace("{{tableComment}}", formatedComment)
            .replace("{{generatedAt}}", LocalDateTime.now().toString())
            .replace("{{tableName}}", tableName)
            .replace("{{className}}", className)
            .replace("{{tableIndexes}}", indexes.toAnnotations().orEmpty())
            .replace("{{fields}}", renderFieldProperties())
            .replace("{{fieldProperties}}", renderFieldProperties())
            .lines()
            .filterNot { it.trim() == IdeaTemplateMarker }
            .joinToString("\n")
            .trimEnd() + "\n"
    }

    private fun KronosTemplate.renderFieldProperties(): String =
        fields.joinToString("\n") { field ->
            buildString {
                field.annotations().forEach { annotation ->
                    append("    ")
                    appendLine(annotation)
                }
                append("    var ${field.name}: ${field.kotlinType}? = null,")
            }
        }
}

const val IdeaTemplateMarker = "// KRONOS_IDEA_TEMPLATE:KPOJO"

private fun KronosIdeaColumn.toField(tableName: String): Field =
    Field(
        columnName = name,
        name = name.toCamelCase(),
        type = sqlType.toKColumnType(),
        primaryKey = when {
            primaryKey && autoGenerated -> PrimaryKeyType.IDENTITY
            primaryKey -> PrimaryKeyType.DEFAULT
            else -> PrimaryKeyType.NOT
        },
        tableName = tableName,
        length = length.takeIf { it > 0 } ?: 0,
        scale = scale.takeIf { it > 0 } ?: 0,
        defaultValue = defaultValue?.takeIf { it.isNotBlank() },
        nullable = nullable,
        kDoc = comment?.takeIf { it.isNotBlank() },
    )

private fun String.toKColumnType(): KColumnType {
    val normalized = trim()
        .substringBefore("(")
        .substringBefore(" ")
        .replace(" ", "_")
        .replace("-", "_")
        .uppercase()
    return when (normalized) {
        "BOOL", "BOOLEAN" -> KColumnType.BIT
        "INTEGER" -> KColumnType.INT
        "INT2" -> KColumnType.SMALLINT
        "INT4" -> KColumnType.INT
        "INT8" -> KColumnType.BIGINT
        "VARCHAR2" -> KColumnType.VARCHAR
        "CHARACTER" -> KColumnType.CHAR
        "CHARACTER_VARYING" -> KColumnType.VARCHAR
        "TIMESTAMPTZ" -> KColumnType.TIMESTAMP
        "DEC" -> KColumnType.DECIMAL
        else -> KColumnType.fromString(normalized)
    }
}

internal fun String.toCamelCase(): String {
    val words = split(Regex("[^A-Za-z0-9]+")).filter { it.isNotBlank() }
    if (words.isEmpty()) return this
    return words.first().lowercase() + words.drop(1).joinToString("") { it.lowercase().replaceFirstChar(Char::titlecase) }
}

internal fun String.toPascalCase(): String =
    toCamelCase().replaceFirstChar(Char::titlecase)
