package com.kotlinorm.plugin.idea.codegen

import com.intellij.database.dataSource.LocalDataSourceManager
import com.intellij.database.model.DasColumn
import com.intellij.database.model.DasDataSource
import com.intellij.database.model.DasIndex
import com.intellij.database.model.DasTable
import com.intellij.database.util.DasUtil
import com.intellij.openapi.project.Project

class KronosDatabaseToolsMetadataProvider(
    private val project: Project,
) : KronosIdeaMetadataProvider {
    override fun loadDataSources(): Result<List<KronosIdeaDataSource>> = runCatching {
        LocalDataSourceManager.getInstance(project).dataSources.map { dataSource ->
            dataSource.toIdeaDataSource()
        }
    }

    private fun DasDataSource.toIdeaDataSource(): KronosIdeaDataSource {
        val tables = DasUtil.getTables(this).toList()
            .filterNot { it.isSystem || it.isTemporary }
            .map { table -> table.toIdeaTable(uniqueId) }
            .sortedBy { it.displayName }
        return KronosIdeaDataSource(
            id = uniqueId,
            name = name,
            tables = tables,
        )
    }

    private fun DasTable.toIdeaTable(dataSourceId: String): KronosIdeaTable =
        KronosIdeaTable(
            dataSourceId = dataSourceId,
            schema = DasUtil.getSchema(this).takeIf { it.isNotBlank() },
            name = name,
            comment = comment.orEmpty(),
            columns = DasUtil.getColumns(this).toList().map { it.toIdeaColumn() },
            indexes = DasUtil.getIndices(this).toList().map { it.toIdeaIndex() },
        )

    private fun DasColumn.toIdeaColumn(): KronosIdeaColumn {
        val dataType = dataType
        return KronosIdeaColumn(
            name = name,
            sqlType = dataType.typeName.ifBlank { dataType.specification },
            nullable = !isNotNull,
            primaryKey = DasUtil.isPrimary(this),
            autoGenerated = DasUtil.isAutoGenerated(this) || DasUtil.isAuto(this),
            length = dataType.length.coerceAtLeast(0),
            scale = dataType.scale.coerceAtLeast(0),
            defaultValue = default,
            comment = comment,
        )
    }

    private fun DasIndex.toIdeaIndex(): KronosIdeaIndex =
        KronosIdeaIndex(
            name = name,
            columns = columnsRef.names().toList(),
            unique = isUnique,
        )
}
