package com.kotlinorm.plugin.idea.codegen

data class KronosIdeaDataSource(
    val id: String,
    val name: String,
    val tables: List<KronosIdeaTable>,
)

data class KronosIdeaTable(
    val dataSourceId: String,
    val schema: String?,
    val name: String,
    val comment: String,
    val columns: List<KronosIdeaColumn>,
    val indexes: List<KronosIdeaIndex> = emptyList(),
) {
    val displayName: String = listOfNotNull(schema, name).joinToString(".")
}

data class KronosIdeaColumn(
    val name: String,
    val sqlType: String,
    val nullable: Boolean,
    val primaryKey: Boolean,
    val autoGenerated: Boolean,
    val length: Int = 0,
    val scale: Int = 0,
    val defaultValue: String? = null,
    val comment: String? = null,
)

data class KronosIdeaIndex(
    val name: String,
    val columns: List<String>,
    val unique: Boolean,
)

data class KronosIdeaGenerationRequest(
    val tables: List<KronosIdeaTable>,
    val packageName: String,
    val outputDirectory: String,
    val overwrite: Boolean,
    val templateName: String,
    val templateContent: String? = null,
)

data class KronosIdeaGeneratedFile(
    val tableName: String,
    val className: String,
    val relativePath: String,
    val content: String,
)

interface KronosIdeaMetadataProvider {
    fun loadDataSources(): Result<List<KronosIdeaDataSource>>
}
