/**
 * Copyright 2022-2026 kronos-orm
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.kotlinorm.idea

import com.intellij.codeInsight.completion.CompletionContributor
import com.intellij.codeInsight.completion.CompletionParameters
import com.intellij.codeInsight.completion.CompletionResultSet
import com.intellij.codeInsight.completion.CompletionType
import com.intellij.codeInsight.lookup.LookupElementBuilder
import com.intellij.openapi.progress.ProcessCanceledException
import com.intellij.psi.PsiElement
import com.kotlinorm.compiler.fir.KronosIdeProjectionModel
import com.kotlinorm.compiler.fir.KronosProjectionIdeBridge
import com.kotlinorm.compiler.utils.GeneratedProjectionPackageFqName
import org.jetbrains.kotlin.analysis.api.analyze
import org.jetbrains.kotlin.analysis.api.components.expressionType
import org.jetbrains.kotlin.analysis.api.types.KaClassType
import org.jetbrains.kotlin.analysis.api.types.KaType
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.psi.KtCallExpression
import org.jetbrains.kotlin.psi.KtDotQualifiedExpression
import org.jetbrains.kotlin.psi.KtExpression
import org.jetbrains.kotlin.psi.KtNameReferenceExpression
import org.jetbrains.kotlin.psi.KtProperty
import org.jetbrains.kotlin.psi.KtQualifiedExpression
import org.jetbrains.kotlin.psi.KtSafeQualifiedExpression
import java.util.concurrent.CancellationException

/**
 * Adds completion items for Kronos FIR-generated projection fields.
 *
 * Kotlin's normal member completion only sees source KPojo members. Derived select fields such
 * as window aliases are generated by the Kronos FIR plugin, so completion reads the same IDE
 * projection snapshot used by hover/documentation.
 */
class KronosProjectionCompletionContributor : CompletionContributor() {
    override fun fillCompletionVariants(parameters: CompletionParameters, result: CompletionResultSet) {
        KronosIdeaSafe.guard("projection completion", Unit) {
            if (parameters.completionType != CompletionType.BASIC) return@guard
            val receiver = parameters.projectionCompletionReceiver() ?: return@guard
            val projectionType = receiver.completionProjectionType() ?: return@guard
            val model = projectionType.findCompletionModel() ?: return@guard
            val fields = if (projectionType.className == model.contextName) model.contextFields else model.fields
            fields.distinctBy { it.name }.forEach { field ->
                result.addElement(
                    LookupElementBuilder.create(field.name.asKotlinIdentifier())
                        .withPresentableText(field.name)
                        .withTypeText(field.type.asRenderableType(), true)
                        .withTailText(" Kronos", true)
                )
            }
        }
    }
}

private data class CompletionProjectionType(
    val classId: ClassId,
    val subjectType: String,
) {
    val className: String = classId.shortClassName.asString()
}

private fun PsiElement.parents(): Sequence<PsiElement> = generateSequence(this) { it.parent }

private fun CompletionParameters.projectionCompletionReceiver(): KtExpression? {
    val reference = position.parents()
        .filterIsInstance<KtNameReferenceExpression>()
        .firstOrNull()
    if (reference != null) {
        reference.qualifiedReceiver()?.let { return it }
    }

    return position.parents()
        .filterIsInstance<KtQualifiedExpression>()
        .firstNotNullOfOrNull { qualified ->
            if (qualified.selectorExpression == null || qualified.textRange.contains(offset)) {
                qualified.receiverExpression
            } else {
                null
            }
        }
}

private fun KtNameReferenceExpression.qualifiedReceiver(): KtExpression? {
    val qualified = parent
    return when (qualified) {
        is KtDotQualifiedExpression -> qualified.receiverExpression.takeIf { qualified.selectorExpression == this }
        is KtSafeQualifiedExpression -> qualified.receiverExpression.takeIf { qualified.selectorExpression == this }
        else -> null
    }
}

private fun KtExpression.completionProjectionType(): CompletionProjectionType? =
    directCompletionProjectionType()
        ?: completionProjectionTypeFromLocalInitializer()
        ?: completionProjectionTypeFromQualifiedReceiver()

private fun KtExpression.directCompletionProjectionType(): CompletionProjectionType? =
    try {
        analyze(this) {
            expressionType?.toCompletionProjectionType()
        }
    } catch (e: ProcessCanceledException) {
        throw e
    } catch (e: CancellationException) {
        throw e
    } catch (_: Throwable) {
        null
    }

private fun KtExpression.completionProjectionTypeFromLocalInitializer(): CompletionProjectionType? {
    val reference = this as? KtNameReferenceExpression ?: return null
    val property = try {
        reference.references
            .asSequence()
            .mapNotNull { it.resolve() }
            .mapNotNull { resolved -> resolved.parents().filterIsInstance<KtProperty>().firstOrNull() }
            .firstOrNull()
    } catch (e: ProcessCanceledException) {
        throw e
    } catch (e: CancellationException) {
        throw e
    } catch (_: Throwable) {
        null
    } ?: return null
    return property.initializer?.completionProjectionType()
}

private fun KtExpression.completionProjectionTypeFromQualifiedReceiver(): CompletionProjectionType? {
    val qualified = this as? KtQualifiedExpression ?: return null
    val selector = qualified.selectorExpression
    val selectorName = (selector as? KtNameReferenceExpression)?.getReferencedName()
        ?: (selector as? KtCallExpression)
            ?.calleeExpression
            ?.let { it as? KtNameReferenceExpression }
            ?.getReferencedName()
    if (selectorName != "firstOrNull" && selectorName != "singleOrNull" && selectorName != "first") return null
    val receiverType = qualified.receiverExpression.completionProjectionType() ?: return null
    val nullable = selectorName == "firstOrNull" || selectorName == "singleOrNull"
    val subjectType = receiverType.classId.asFqNameString() + if (nullable) "?" else ""
    return CompletionProjectionType(receiverType.classId, subjectType)
}

private fun KaType.toCompletionProjectionType(): CompletionProjectionType? {
    val type = this as? KaClassType ?: return null
    val directClassId = type.classId.takeIf { it.isCompletionProjectionClassId() }
    if (directClassId != null) return CompletionProjectionType(directClassId, renderCompletionProjectionTypeText())
    val argumentClassId = type.typeArguments.firstOrNull()
        ?.type
        ?.let { it as? KaClassType }
        ?.classId
        ?.takeIf { it.isCompletionProjectionClassId() }
        ?: return null
    return CompletionProjectionType(argumentClassId, renderCompletionProjectionTypeText())
}

private fun KaType.renderCompletionProjectionTypeText(): String {
    val classType = this as? KaClassType ?: return toString()
    val args = classType.typeArguments
        .mapNotNull { it.type?.renderCompletionProjectionTypeText() }
        .takeIf { it.isNotEmpty() }
        ?.joinToString(prefix = "<", postfix = ">")
        .orEmpty()
    return classType.classId.asFqNameString() + args + if (toString().trim().endsWith("?")) "?" else ""
}

private fun ClassId.isCompletionProjectionClassId(): Boolean {
    if (packageFqName != GeneratedProjectionPackageFqName) return false
    val className = shortClassName.asString()
    return className.startsWith("KronosSelectContext_") || className.startsWith("KronosSelectResult_")
}

private fun CompletionProjectionType.findCompletionModel(): KronosIdeProjectionModel? =
    KronosProjectionIdeBridge.read().firstOrNull { it.name == className || it.contextName == className }
