/**
 * Copyright 2022-2026 kronos-orm
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.kotlinorm.idea

import com.intellij.codeInsight.completion.CompletionContributor
import com.intellij.codeInsight.completion.CompletionParameters
import com.intellij.codeInsight.completion.CompletionResultSet
import com.intellij.codeInsight.completion.CompletionType
import com.intellij.codeInsight.lookup.LookupElementBuilder
import com.intellij.openapi.progress.ProcessCanceledException
import com.intellij.psi.PsiElement
import com.kotlinorm.compiler.fir.KronosProjectionIdeBridge
import org.jetbrains.kotlin.analysis.api.analyze
import org.jetbrains.kotlin.analysis.api.components.expressionType
import org.jetbrains.kotlin.psi.KtCallExpression
import org.jetbrains.kotlin.psi.KtDotQualifiedExpression
import org.jetbrains.kotlin.psi.KtExpression
import org.jetbrains.kotlin.psi.KtNameReferenceExpression
import org.jetbrains.kotlin.psi.KtProperty
import org.jetbrains.kotlin.psi.KtQualifiedExpression
import org.jetbrains.kotlin.psi.KtSafeQualifiedExpression
import java.util.concurrent.CancellationException

/**
 * Adds completion items for Kronos FIR-generated projection fields.
 *
 * Kotlin's normal member completion only sees source KPojo members. Derived select fields such
 * as window aliases are generated by the Kronos FIR plugin, so completion reads the same IDE
 * projection snapshot used by hover/documentation.
 */
class KronosProjectionCompletionContributor : CompletionContributor() {
    override fun fillCompletionVariants(parameters: CompletionParameters, result: CompletionResultSet) {
        KronosIdeaSafe.guard("projection completion", Unit) {
            if (parameters.completionType != CompletionType.BASIC) return@guard
            val receiver = parameters.projectionCompletionReceiver() ?: return@guard
            val projectionType = receiver.completionProjectionType() ?: return@guard
            val fields = projectionType.findCompletionFields() ?: return@guard
            fields.distinctBy { it.name }.forEach { field ->
                result.addElement(
                    LookupElementBuilder.create(field.name.asKotlinIdentifier())
                        .withPresentableText(field.name)
                        .withTypeText(field.type.asRenderableType(), true)
                        .withTailText(" Kronos", true)
                )
            }
        }
    }
}

private fun PsiElement.parents(): Sequence<PsiElement> = generateSequence(this) { it.parent }

private fun CompletionParameters.projectionCompletionReceiver(): KtExpression? {
    val reference = position.parents()
        .filterIsInstance<KtNameReferenceExpression>()
        .firstOrNull()
    if (reference != null) {
        reference.qualifiedReceiver()?.let { return it }
    }

    return position.parents()
        .filterIsInstance<KtQualifiedExpression>()
        .firstNotNullOfOrNull { qualified ->
            if (qualified.selectorExpression == null || qualified.textRange.contains(offset)) {
                qualified.receiverExpression
            } else {
                null
            }
        }
}

private fun KtNameReferenceExpression.qualifiedReceiver(): KtExpression? {
    val qualified = parent
    return when (qualified) {
        is KtDotQualifiedExpression -> qualified.receiverExpression.takeIf { qualified.selectorExpression == this }
        is KtSafeQualifiedExpression -> qualified.receiverExpression.takeIf { qualified.selectorExpression == this }
        else -> null
    }
}

private fun KtExpression.completionProjectionType(): KronosProjectionType? =
    discoveredProjectionType()?.takeIf { it.isDirectCompletionReceiver }

private fun KtExpression.discoveredProjectionType(): KronosProjectionType? =
    analyzedProjectionType()
        ?: projectionTypeFromLocalInitializer()
        ?: projectionTypeFromQualifiedReceiver()

private fun KtExpression.analyzedProjectionType(): KronosProjectionType? =
    try {
        analyze(this) {
            expressionType?.toKronosProjectionType()
        }
    } catch (e: ProcessCanceledException) {
        throw e
    } catch (e: CancellationException) {
        throw e
    } catch (_: Throwable) {
        null
    }

private fun KtExpression.projectionTypeFromLocalInitializer(): KronosProjectionType? {
    val reference = this as? KtNameReferenceExpression ?: return null
    val property = try {
        reference.references
            .asSequence()
            .mapNotNull { it.resolve() }
            .mapNotNull { resolved -> resolved.parents().filterIsInstance<KtProperty>().firstOrNull() }
            .firstOrNull()
    } catch (e: ProcessCanceledException) {
        throw e
    } catch (e: CancellationException) {
        throw e
    } catch (_: Throwable) {
        null
    } ?: return null
    return property.initializer?.discoveredProjectionType()
}

private fun KtExpression.projectionTypeFromQualifiedReceiver(): KronosProjectionType? {
    val qualified = this as? KtQualifiedExpression ?: return null
    val selector = qualified.selectorExpression
    val selectorName = (selector as? KtNameReferenceExpression)?.getReferencedName()
        ?: (selector as? KtCallExpression)
            ?.calleeExpression
            ?.let { it as? KtNameReferenceExpression }
            ?.getReferencedName()
    if (selectorName != "firstOrNull" && selectorName != "singleOrNull" && selectorName != "first") return null
    val receiverType = qualified.receiverExpression.discoveredProjectionType()
        ?.takeIf { it.canExtractDirectRow }
        ?: return null
    val nullable = selectorName == "firstOrNull" || selectorName == "singleOrNull"
    return receiverType.asDirectCompletionReceiver(nullable)
}

private fun KronosProjectionType.findCompletionFields() =
    KronosProjectionIdeBridge.read().canonicalProjectionClassDeclaration(className)?.fields
