/*
 * Copyright 2022-2026 kronos-orm
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 */

package com.kotlinorm.orm.join

import com.kotlinorm.interfaces.KPojo

// Generated by build-logic/scripts/codegen.gradle.kts.

class JoinSource2<T1 : KPojo, T2 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource2<T1, T2>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource2<T1, T2> =
        JoinSource2(state)
}

class JoinSource3<T1 : KPojo, T2 : KPojo, T3 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource3<T1, T2, T3>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource3<T1, T2, T3> =
        JoinSource3(state)
}

class JoinSource4<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource4<T1, T2, T3, T4>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource4<T1, T2, T3, T4> =
        JoinSource4(state)
}

class JoinSource5<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource5<T1, T2, T3, T4, T5>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource5<T1, T2, T3, T4, T5> =
        JoinSource5(state)
}

class JoinSource6<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource6<T1, T2, T3, T4, T5, T6>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource6<T1, T2, T3, T4, T5, T6> =
        JoinSource6(state)
}

class JoinSource7<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo, T7 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource7<T1, T2, T3, T4, T5, T6, T7>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource7<T1, T2, T3, T4, T5, T6, T7> =
        JoinSource7(state)
}

class JoinSource8<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo, T7 : KPojo, T8 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource8<T1, T2, T3, T4, T5, T6, T7, T8>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource8<T1, T2, T3, T4, T5, T6, T7, T8> =
        JoinSource8(state)
}

class JoinSource9<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo, T7 : KPojo, T8 : KPojo, T9 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource9<T1, T2, T3, T4, T5, T6, T7, T8, T9>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource9<T1, T2, T3, T4, T5, T6, T7, T8, T9> =
        JoinSource9(state)
}

class JoinSource10<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo, T7 : KPojo, T8 : KPojo, T9 : KPojo, T10 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> =
        JoinSource10(state)
}

class JoinSource11<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo, T7 : KPojo, T8 : KPojo, T9 : KPojo, T10 : KPojo, T11 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> =
        JoinSource11(state)
}

class JoinSource12<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo, T7 : KPojo, T8 : KPojo, T9 : KPojo, T10 : KPojo, T11 : KPojo, T12 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> =
        JoinSource12(state)
}

class JoinSource13<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo, T7 : KPojo, T8 : KPojo, T9 : KPojo, T10 : KPojo, T11 : KPojo, T12 : KPojo, T13 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> =
        JoinSource13(state)
}

class JoinSource14<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo, T7 : KPojo, T8 : KPojo, T9 : KPojo, T10 : KPojo, T11 : KPojo, T12 : KPojo, T13 : KPojo, T14 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> =
        JoinSource14(state)
}

class JoinSource15<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo, T7 : KPojo, T8 : KPojo, T9 : KPojo, T10 : KPojo, T11 : KPojo, T12 : KPojo, T13 : KPojo, T14 : KPojo, T15 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> =
        JoinSource15(state)
}

class JoinSource16<T1 : KPojo, T2 : KPojo, T3 : KPojo, T4 : KPojo, T5 : KPojo, T6 : KPojo, T7 : KPojo, T8 : KPojo, T9 : KPojo, T10 : KPojo, T11 : KPojo, T12 : KPojo, T13 : KPojo, T14 : KPojo, T15 : KPojo, T16 : KPojo> @PublishedApi internal constructor(
    state: JoinSourceState<T1>
) : JoinSource<T1, JoinSource16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>>(state) {
    @PublishedApi
    internal override fun recreate(state: JoinSourceState<T1>): JoinSource16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> =
        JoinSource16(state)
}
