/**
 * Copyright 2022-2026 kronos-orm
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.kotlinorm.interfaces

import com.kotlinorm.Kronos.createTimeStrategy
import com.kotlinorm.Kronos.logicDeleteStrategy
import com.kotlinorm.Kronos.optimisticLockStrategy
import com.kotlinorm.Kronos.updateTimeStrategy
import com.kotlinorm.annotations.Ignore
import com.kotlinorm.beans.config.KronosCommonStrategy
import com.kotlinorm.beans.dsl.Field
import com.kotlinorm.beans.dsl.KTableIndex
import com.kotlinorm.enums.IgnoreAction
import kotlin.reflect.KClass

/**
 * Kronos Pojo Class
 *
 * Interface for data class to be used in kronos
 * after extending [KPojo], a data class can be recognized as a table class in Kronos-orm
 *
 * @author OUSC
 */
interface KPojo {
    /**
     * kronos KClass
     *
     * The KClass of the KPojo.
     *
     * **the backing field of this property will be generated by the compiler plugin**
     */
    @Suppress("PropertyName")
    @Ignore([IgnoreAction.ALL])
    var __kClass: KClass<out KPojo>
        get() = KPojo::class
        set(_) {}

    /**
     * toDataMap
     *
     * Transform the KPojo into a mutable map where the keys are strings and the values are nullable Any types.
     *
     * **the body of this function will be generated by the compiler plugin**
     * @return mutableMapOf<String, Any?>
     */
    fun toDataMap() = mutableMapOf<String, Any?>()

    /**
     * fromMapData
     *
     * Transform the mutable map into a KPojo
     *
     * **the body of this function will be generated by the compiler plugin**
     * @return KPojo
     */
    @Suppress("UNCHECKED_CAST")
    fun <T : KPojo> safeFromMapData(map: Map<String, Any?>) = this as T

    /**
     * fromMapData
     *
     * Transform the mutable map into a KPojo
     *
     * **the body of this function will be generated by the compiler plugin**
     * @return KPojo
     */
    @Suppress("UNCHECKED_CAST")
    fun <T : KPojo> fromMapData(map: Map<String, Any?>) = this as T

    /**
     * get
     *
     * Get the value of the field by name
     *
     * **the body of this function will be generated by the compiler plugin**
     * @param name the name of the field
     * @return Any?
     */
    operator fun get(name: String): Any? = null

    /**
     * set
     *
     * Set the value of the field by name
     *
     * **the body of this function will be generated by the compiler plugin**
     * @param name the name of the field
     * @param value the value of the field
     */
    operator fun set(name: String, value: Any?){}

    /**
     * kronos TableName
     *
     * The name of the table
     *
     * **the body of this function will be generated by the compiler plugin**
     * @return String
     */
    @Suppress("PropertyName")
    @Ignore([IgnoreAction.ALL])
    var __tableName: String
        get() = error("__tableName must be overridden by the compiler plugin")
        set(_) {}

    /**
     * kronosTableComment
     *
     * The comment of the table
     *
     * **the body of this function will be generated by the compiler plugin**
     * @return String
     */
    @Suppress("PropertyName")
    @Ignore([IgnoreAction.ALL])
    var __tableComment: String
        get() = error("__tableComment must be overridden by the compiler plugin")
        set(_) {}

    /**
     * kronos columns
     *
     * A list of fields to be recognized as columns in the table.
     *
     * **the backing field of this property will be generated by the compiler plugin**
     */
    @Suppress("PropertyName")
    @Ignore([IgnoreAction.ALL])
    var __columns: MutableList<Field>
        get() = mutableListOf()
        set(_) {}

    /**
     * kronos table indexes
     *
     * The table indexes.
     *
     * **the backing field of this property will be generated by the compiler plugin**
     */
    @Suppress("PropertyName")
    @Ignore([IgnoreAction.ALL])
    var __tableIndexes: MutableList<KTableIndex>
        get() = mutableListOf()
        set(_) {}

    /**
     * kronos create-time strategy
     *
     * Common strategy to be recognized as the create_time.
     *
     * **the backing field of this property will be generated by the compiler plugin**
     */
    @Suppress("PropertyName")
    @Ignore([IgnoreAction.ALL])
    var __createTime: KronosCommonStrategy
        get() = createTimeStrategy
        set(_) {}

    /**
     * kronos update-time strategy
     *
     * Common strategy to be recognized as the update_time.
     *
     * **the backing field of this property will be generated by the compiler plugin**
     */
    @Suppress("PropertyName")
    @Ignore([IgnoreAction.ALL])
    var __updateTime: KronosCommonStrategy
        get() = updateTimeStrategy
        set(_) {}

    /**
     * kronos logic-delete strategy
     *
     * Common strategy to be recognized as the logic_delete.
     *
     * **the backing field of this property will be generated by the compiler plugin**
     */
    @Suppress("PropertyName")
    @Ignore([IgnoreAction.ALL])
    var __logicDelete: KronosCommonStrategy
        get() = logicDeleteStrategy
        set(_) {}

    /**
     * kronos optimistic-lock strategy
     *
     * Common strategy to be recognized as the optimistic_lock.
     *
     * **the backing field of this property will be generated by the compiler plugin**
     */
    @Suppress("PropertyName")
    @Ignore([IgnoreAction.ALL])
    var __optimisticLock: KronosCommonStrategy
        get() = optimisticLockStrategy
        set(_) {}
}
