/**
 * Copyright 2022-2026 kronos-orm
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.kotlinorm.idea

import com.kotlinorm.plugin.idea.codegen.BuiltInKPojoName
import com.kotlinorm.plugin.idea.codegen.BuiltInKPojoTemplate
import com.kotlinorm.plugin.idea.codegen.IdeaTemplateMarker
import com.kotlinorm.plugin.idea.codegen.KronosIdeaCodegenRenderer
import com.kotlinorm.plugin.idea.codegen.KronosIdeaColumn
import com.kotlinorm.plugin.idea.codegen.KronosIdeaGenerationRequest
import com.kotlinorm.plugin.idea.codegen.KronosIdeaTable
import java.nio.file.Files
import java.nio.file.Paths
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

class KronosIdeaCodegenRendererTest {
    @Test
    fun `preview renders deterministic kpojo text from ide metadata`() {
        val files = KronosIdeaCodegenRenderer().preview(
            KronosIdeaGenerationRequest(
                tables = listOf(
                    KronosIdeaTable(
                        dataSourceId = "main",
                        schema = "public",
                        name = "tb_user",
                        comment = "User table",
                        columns = listOf(
                            KronosIdeaColumn(
                                name = "id",
                                sqlType = "INT",
                                nullable = false,
                                primaryKey = true,
                                autoGenerated = true,
                            ),
                            KronosIdeaColumn(
                                name = "user_name",
                                sqlType = "VARCHAR",
                                nullable = false,
                                primaryKey = false,
                                autoGenerated = false,
                                length = 64,
                            ),
                        ),
                    ),
                ),
                packageName = "com.example.orm",
                outputDirectory = "build/generated/kronos",
                overwrite = false,
                templateName = BuiltInKPojoName,
            )
        )

        assertEquals(1, files.size)
        assertEquals("TbUser", files.single().className)
        val content = files.single().content
        assertTrue(content.contains("package com.example.orm"))
        assertTrue(content.contains("@Table(name = \"tb_user\")"))
        assertTrue(content.contains("@PrimaryKey(identity = true)"))
        assertTrue(content.contains("@NonNull"))
        assertTrue(content.contains("var userName: String? = null,"))
    }

    @Test
    fun `preview uses selected project kpojo template content`() {
        val files = KronosIdeaCodegenRenderer().preview(
            fixtureRequest(
                templateName = "KPojo",
                templateContent = """
                    $IdeaTemplateMarker
                    package {{packageName}}

                    {{imports}}

                    // custom project template for {{tableName}}
                    @Table(name = "{{tableName}}")
                    data class {{className}}(
                    {{fields}}
                    ): KPojo
                """.trimIndent(),
            )
        )

        val content = files.single().content
        assertTrue(content.contains("// custom project template for tb_user"))
        assertTrue(content.contains("data class TbUser("))
        assertTrue(content.contains("var userName: String? = null,"))
    }

    @Test
    fun `preview rejects unsupported project template instead of falling back silently`() {
        val error = assertFailsWith<IllegalStateException> {
            KronosIdeaCodegenRenderer().preview(
                fixtureRequest(
                    templateName = "LegacyKts",
                    templateContent = "template { +\"package ${'$'}packageName\" }",
                )
            )
        }

        assertTrue(error.message.orEmpty().contains("not a supported IDEA KPojo template"))
    }

    @Test
    fun `built in kpojo template content is inspectable and copyable`() {
        assertTrue(BuiltInKPojoTemplate.contains(IdeaTemplateMarker))
        assertTrue(BuiltInKPojoTemplate.contains("package {{packageName}}"))
        assertTrue(BuiltInKPojoTemplate.contains("data class {{className}}("))

        val managerSource = Files.readString(
            Paths.get("src/main/kotlin/com/kotlinorm/plugin/idea/codegen/KronosTemplateManager.kt")
        )
        assertTrue(managerSource.contains("fun content(template: KronosIdeaTemplate): String"))
        assertTrue(managerSource.contains("projectTemplates + KronosIdeaTemplate"))

        val mainPanelSource = Files.readString(
            Paths.get("src/main/kotlin/com/kotlinorm/plugin/idea/MainPanel.kt")
        )
        assertTrue(mainPanelSource.contains("templatePreviewArea"))
        assertTrue(mainPanelSource.contains("Copy to Project"))
        assertTrue(mainPanelSource.contains("Open Project Template"))
        assertTrue(mainPanelSource.contains("template.path"))
    }

    private fun fixtureRequest(
        templateName: String = BuiltInKPojoName,
        templateContent: String? = null,
    ): KronosIdeaGenerationRequest =
        KronosIdeaGenerationRequest(
            tables = listOf(
                KronosIdeaTable(
                    dataSourceId = "main",
                    schema = "public",
                    name = "tb_user",
                    comment = "User table",
                    columns = listOf(
                        KronosIdeaColumn(
                            name = "id",
                            sqlType = "INT",
                            nullable = false,
                            primaryKey = true,
                            autoGenerated = true,
                        ),
                        KronosIdeaColumn(
                            name = "user_name",
                            sqlType = "VARCHAR",
                            nullable = false,
                            primaryKey = false,
                            autoGenerated = false,
                            length = 64,
                        ),
                    ),
                ),
            ),
            packageName = "com.example.orm",
            outputDirectory = "build/generated/kronos",
            overwrite = false,
            templateName = templateName,
            templateContent = templateContent,
        )
}
