package com.kotlinorm.integration

import com.kotlinorm.integration.profiles.StandardIntegrationScenarioProfile
import com.kotlinorm.integration.suites.CascadeIntegrationSuite
import com.kotlinorm.integration.suites.CodegenIntegrationSuite
import com.kotlinorm.integration.suites.ComplexQueryProjectionIntegrationSuite
import com.kotlinorm.integration.suites.CrudWhereIntegrationSuite
import com.kotlinorm.integration.suites.DmlSubqueryIntegrationSuite
import com.kotlinorm.integration.suites.DmlUpsertCornerCaseIntegrationSuite
import com.kotlinorm.integration.suites.DslEdgeCaseIntegrationSuite
import com.kotlinorm.integration.suites.EdgeCaseIntegrationSuite
import com.kotlinorm.integration.suites.ErrorIntegrationSuite
import com.kotlinorm.integration.suites.FunctionAndParameterIntegrationSuite
import com.kotlinorm.integration.suites.QueryIntegrationSuite
import com.kotlinorm.integration.suites.ResultMethodEdgeIntegrationSuite
import com.kotlinorm.integration.suites.SafetyCornerCaseIntegrationSuite
import com.kotlinorm.integration.suites.SchemaIntegrationSuite
import com.kotlinorm.integration.suites.SchemaSyncRegressionSuite
import com.kotlinorm.integration.suites.StrategyIntegrationSuite
import com.kotlinorm.integration.suites.TransactionIntegrationSuite
import com.kotlinorm.integration.suites.TypeDialectDdlCornerIntegrationSuite
import com.kotlinorm.integration.suites.UpsertIntegrationSuite
import com.kotlinorm.integration.suites.ValueTypeIntegrationSuite
import com.kotlinorm.integration.suites.WrapperSqlIntegrationSuite
import com.kotlinorm.integration.support.IntegrationDatabaseEnvironments.mysql

class MysqlSchemaIntegrationTest : SchemaIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlSchemaSyncRegressionTest : SchemaSyncRegressionSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlCrudWhereIntegrationTest : CrudWhereIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlQueryIntegrationTest : QueryIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlResultMethodEdgeIntegrationTest : ResultMethodEdgeIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlDslEdgeCaseIntegrationTest : DslEdgeCaseIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlComplexQueryProjectionIntegrationTest : ComplexQueryProjectionIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlDmlSubqueryIntegrationTest : DmlSubqueryIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlDmlUpsertCornerCaseIntegrationTest : DmlUpsertCornerCaseIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlUpsertIntegrationTest : UpsertIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlErrorIntegrationTest : ErrorIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlWrapperSqlIntegrationTest : WrapperSqlIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlCascadeIntegrationTest : CascadeIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlValueTypeIntegrationTest : ValueTypeIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlTypeDialectDdlCornerIntegrationTest : TypeDialectDdlCornerIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlFunctionAndParameterIntegrationTest : FunctionAndParameterIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlTransactionIntegrationTest : TransactionIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlSafetyCornerCaseIntegrationTest : SafetyCornerCaseIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlEdgeCaseIntegrationTest : EdgeCaseIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
class MysqlCodegenIntegrationTest : CodegenIntegrationSuite(mysql)
class MysqlStrategyIntegrationTest : StrategyIntegrationSuite(mysql, StandardIntegrationScenarioProfile)
