package com.kotlinorm.integration

import com.kotlinorm.integration.profiles.StandardIntegrationScenarioProfile
import com.kotlinorm.integration.suites.CascadeIntegrationSuite
import com.kotlinorm.integration.suites.ComplexQueryProjectionIntegrationSuite
import com.kotlinorm.integration.suites.CrudWhereIntegrationSuite
import com.kotlinorm.integration.suites.DmlSubqueryIntegrationSuite
import com.kotlinorm.integration.suites.DmlUpsertCornerCaseIntegrationSuite
import com.kotlinorm.integration.suites.DslEdgeCaseIntegrationSuite
import com.kotlinorm.integration.suites.EdgeCaseIntegrationSuite
import com.kotlinorm.integration.suites.ErrorIntegrationSuite
import com.kotlinorm.integration.suites.FunctionAndParameterIntegrationSuite
import com.kotlinorm.integration.suites.OracleCompatibleFunctionSemanticsIntegrationSuite
import com.kotlinorm.integration.suites.QueryIntegrationSuite
import com.kotlinorm.integration.suites.ResultMethodEdgeIntegrationSuite
import com.kotlinorm.integration.suites.SafetyCornerCaseIntegrationSuite
import com.kotlinorm.integration.suites.SchemaIntegrationSuite
import com.kotlinorm.integration.suites.SchemaSyncRegressionSuite
import com.kotlinorm.integration.suites.StrategyIntegrationSuite
import com.kotlinorm.integration.suites.TransactionIntegrationSuite
import com.kotlinorm.integration.suites.TypeDialectDdlCornerIntegrationSuite
import com.kotlinorm.integration.suites.UpsertIntegrationSuite
import com.kotlinorm.integration.suites.ValueTypeIntegrationSuite
import com.kotlinorm.integration.suites.WrapperSqlIntegrationSuite
import com.kotlinorm.integration.support.IntegrationDatabaseEnvironments.oracle

class OracleSchemaIntegrationTest : SchemaIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleSchemaSyncRegressionTest : SchemaSyncRegressionSuite(oracle, StandardIntegrationScenarioProfile)
class OracleCrudWhereIntegrationTest : CrudWhereIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleQueryIntegrationTest : QueryIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleResultMethodEdgeIntegrationTest : ResultMethodEdgeIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleDslEdgeCaseIntegrationTest : DslEdgeCaseIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleComplexQueryProjectionIntegrationTest : ComplexQueryProjectionIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleDmlSubqueryIntegrationTest : DmlSubqueryIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleDmlUpsertCornerCaseIntegrationTest : DmlUpsertCornerCaseIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleUpsertIntegrationTest : UpsertIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleErrorIntegrationTest : ErrorIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleWrapperSqlIntegrationTest : WrapperSqlIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleCascadeIntegrationTest : CascadeIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleValueTypeIntegrationTest : ValueTypeIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleTypeDialectDdlCornerIntegrationTest : TypeDialectDdlCornerIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleFunctionAndParameterIntegrationTest : FunctionAndParameterIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleFunctionSemanticsIntegrationTest : OracleCompatibleFunctionSemanticsIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleTransactionIntegrationTest : TransactionIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleSafetyCornerCaseIntegrationTest : SafetyCornerCaseIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleEdgeCaseIntegrationTest : EdgeCaseIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleStrategyIntegrationTest : StrategyIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
