package com.kotlinorm.integration

import com.kotlinorm.integration.profiles.StandardIntegrationScenarioProfile
import com.kotlinorm.integration.suites.CascadeIntegrationSuite
import com.kotlinorm.integration.suites.CrudWhereIntegrationSuite
import com.kotlinorm.integration.suites.DmlSubqueryIntegrationSuite
import com.kotlinorm.integration.suites.ErrorIntegrationSuite
import com.kotlinorm.integration.suites.FunctionAndParameterIntegrationSuite
import com.kotlinorm.integration.suites.QueryIntegrationSuite
import com.kotlinorm.integration.suites.SchemaIntegrationSuite
import com.kotlinorm.integration.suites.SchemaSyncRegressionSuite
import com.kotlinorm.integration.suites.TransactionIntegrationSuite
import com.kotlinorm.integration.suites.UpsertIntegrationSuite
import com.kotlinorm.integration.suites.ValueTypeIntegrationSuite
import com.kotlinorm.integration.suites.WrapperSqlIntegrationSuite
import com.kotlinorm.integration.support.IntegrationDatabaseEnvironments.oracle

class OracleSchemaIntegrationTest : SchemaIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleSchemaSyncRegressionTest : SchemaSyncRegressionSuite(oracle, StandardIntegrationScenarioProfile)
class OracleCrudWhereIntegrationTest : CrudWhereIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleQueryIntegrationTest : QueryIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleDmlSubqueryIntegrationTest : DmlSubqueryIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleUpsertIntegrationTest : UpsertIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleErrorIntegrationTest : ErrorIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleWrapperSqlIntegrationTest : WrapperSqlIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleCascadeIntegrationTest : CascadeIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleValueTypeIntegrationTest : ValueTypeIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleFunctionAndParameterIntegrationTest : FunctionAndParameterIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
class OracleTransactionIntegrationTest : TransactionIntegrationSuite(oracle, StandardIntegrationScenarioProfile)
