package com.kotlinorm.integration

import com.kotlinorm.integration.profiles.StandardIntegrationScenarioProfile
import com.kotlinorm.integration.suites.CascadeIntegrationSuite
import com.kotlinorm.integration.suites.CrudWhereIntegrationSuite
import com.kotlinorm.integration.suites.DmlSubqueryIntegrationSuite
import com.kotlinorm.integration.suites.DslEdgeCaseIntegrationSuite
import com.kotlinorm.integration.suites.EdgeCaseIntegrationSuite
import com.kotlinorm.integration.suites.ErrorIntegrationSuite
import com.kotlinorm.integration.suites.FunctionAndParameterIntegrationSuite
import com.kotlinorm.integration.suites.QueryIntegrationSuite
import com.kotlinorm.integration.suites.ResultMethodEdgeIntegrationSuite
import com.kotlinorm.integration.suites.SchemaIntegrationSuite
import com.kotlinorm.integration.suites.SchemaSyncRegressionSuite
import com.kotlinorm.integration.suites.StrategyIntegrationSuite
import com.kotlinorm.integration.suites.TransactionIntegrationSuite
import com.kotlinorm.integration.suites.UpsertIntegrationSuite
import com.kotlinorm.integration.suites.ValueTypeIntegrationSuite
import com.kotlinorm.integration.suites.WrapperSqlIntegrationSuite
import com.kotlinorm.integration.support.IntegrationDatabaseEnvironments.postgres

class PostgresSchemaIntegrationTest : SchemaIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresSchemaSyncRegressionTest : SchemaSyncRegressionSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresCrudWhereIntegrationTest : CrudWhereIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresQueryIntegrationTest : QueryIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresResultMethodEdgeIntegrationTest : ResultMethodEdgeIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresDslEdgeCaseIntegrationTest : DslEdgeCaseIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresDmlSubqueryIntegrationTest : DmlSubqueryIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresUpsertIntegrationTest : UpsertIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresErrorIntegrationTest : ErrorIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresWrapperSqlIntegrationTest : WrapperSqlIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresCascadeIntegrationTest : CascadeIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresValueTypeIntegrationTest : ValueTypeIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresFunctionAndParameterIntegrationTest : FunctionAndParameterIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresTransactionIntegrationTest : TransactionIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresEdgeCaseIntegrationTest : EdgeCaseIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
class PostgresStrategyIntegrationTest : StrategyIntegrationSuite(postgres, StandardIntegrationScenarioProfile)
