package com.kotlinorm.integration

import com.kotlinorm.integration.profiles.StandardIntegrationScenarioProfile
import com.kotlinorm.integration.suites.CascadeIntegrationSuite
import com.kotlinorm.integration.suites.CrudWhereIntegrationSuite
import com.kotlinorm.integration.suites.DmlSubqueryIntegrationSuite
import com.kotlinorm.integration.suites.DslEdgeCaseIntegrationSuite
import com.kotlinorm.integration.suites.EdgeCaseIntegrationSuite
import com.kotlinorm.integration.suites.ErrorIntegrationSuite
import com.kotlinorm.integration.suites.FunctionAndParameterIntegrationSuite
import com.kotlinorm.integration.suites.QueryIntegrationSuite
import com.kotlinorm.integration.suites.ResultMethodEdgeIntegrationSuite
import com.kotlinorm.integration.suites.SchemaIntegrationSuite
import com.kotlinorm.integration.suites.SchemaSyncRegressionSuite
import com.kotlinorm.integration.suites.StrategyIntegrationSuite
import com.kotlinorm.integration.suites.TransactionIntegrationSuite
import com.kotlinorm.integration.suites.UpsertIntegrationSuite
import com.kotlinorm.integration.suites.ValueTypeIntegrationSuite
import com.kotlinorm.integration.suites.WrapperSqlIntegrationSuite
import com.kotlinorm.integration.support.IntegrationDatabaseEnvironments.sqlite

class SqliteSchemaIntegrationTest : SchemaIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteSchemaSyncRegressionTest : SchemaSyncRegressionSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteCrudWhereIntegrationTest : CrudWhereIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteQueryIntegrationTest : QueryIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteResultMethodEdgeIntegrationTest : ResultMethodEdgeIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteDslEdgeCaseIntegrationTest : DslEdgeCaseIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteDmlSubqueryIntegrationTest : DmlSubqueryIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteUpsertIntegrationTest : UpsertIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteErrorIntegrationTest : ErrorIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteWrapperSqlIntegrationTest : WrapperSqlIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteCascadeIntegrationTest : CascadeIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteValueTypeIntegrationTest : ValueTypeIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteFunctionAndParameterIntegrationTest : FunctionAndParameterIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteTransactionIntegrationTest : TransactionIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteEdgeCaseIntegrationTest : EdgeCaseIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
class SqliteStrategyIntegrationTest : StrategyIntegrationSuite(sqlite, StandardIntegrationScenarioProfile)
