package com.kotlinorm.integration

import com.kotlinorm.integration.profiles.StandardIntegrationScenarioProfile
import com.kotlinorm.integration.suites.CascadeIntegrationSuite
import com.kotlinorm.integration.suites.CrudWhereIntegrationSuite
import com.kotlinorm.integration.suites.DmlSubqueryIntegrationSuite
import com.kotlinorm.integration.suites.DslEdgeCaseIntegrationSuite
import com.kotlinorm.integration.suites.EdgeCaseIntegrationSuite
import com.kotlinorm.integration.suites.ErrorIntegrationSuite
import com.kotlinorm.integration.suites.FunctionAndParameterIntegrationSuite
import com.kotlinorm.integration.suites.QueryIntegrationSuite
import com.kotlinorm.integration.suites.ResultMethodEdgeIntegrationSuite
import com.kotlinorm.integration.suites.SchemaIntegrationSuite
import com.kotlinorm.integration.suites.SchemaSyncRegressionSuite
import com.kotlinorm.integration.suites.TransactionIntegrationSuite
import com.kotlinorm.integration.suites.UpsertIntegrationSuite
import com.kotlinorm.integration.suites.ValueTypeIntegrationSuite
import com.kotlinorm.integration.suites.WrapperSqlIntegrationSuite
import com.kotlinorm.integration.support.IntegrationDatabaseEnvironments.sqlServer

class SqlServerSchemaIntegrationTest : SchemaIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerSchemaSyncRegressionTest : SchemaSyncRegressionSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerCrudWhereIntegrationTest : CrudWhereIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerQueryIntegrationTest : QueryIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerResultMethodEdgeIntegrationTest : ResultMethodEdgeIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerDslEdgeCaseIntegrationTest : DslEdgeCaseIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerDmlSubqueryIntegrationTest : DmlSubqueryIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerUpsertIntegrationTest : UpsertIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerErrorIntegrationTest : ErrorIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerWrapperSqlIntegrationTest : WrapperSqlIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerCascadeIntegrationTest : CascadeIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerValueTypeIntegrationTest : ValueTypeIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerFunctionAndParameterIntegrationTest : FunctionAndParameterIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerTransactionIntegrationTest : TransactionIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
class SqlServerEdgeCaseIntegrationTest : EdgeCaseIntegrationSuite(sqlServer, StandardIntegrationScenarioProfile)
